services:
  php:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile

    networks:
      - sonata-net
    environment:
      - APP_ENV=dev

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./Docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - sonata-net

networks:
  sonata-net:
    driver: bridge